name: Tests
run-name: Mocha tests

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install the project dependencies
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run tests
        run: npm run test

      # Cancel the commit and close the pull request if the tests fail
      - name: Cancel commit on failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const sha = context.sha;
            await github.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: sha,
                state: 'failure',
                context: 'Tests',
                description: 'Tests failed',
            });
