name: Tests
run-name: Mocha tests

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v3

      # Install the project dependencies
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run tests
        run: npm run test

      # Cancel the commit and close the pull request if the tests fail
      - name: Cancel commit on failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            console.log("${{ github }}")
            const { default: script } = await import('${{ github.repository }}/scripts/revert-commit');
            await script({ github, context });
